In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv("adult.csv")
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

## Task 1

In [7]:
print(df.isnull().sum())

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [10]:
df.replace(" ?", np.nan, inplace=True)
df.replace("?", np.nan, inplace=True)
print(df.isnull().sum())

age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     583
income               0
dtype: int64

## Task 2

In [9]:
missing_count=df.isnull().sum()
missing_percent=(df.isnull().sum()/len(df))*100
missing_summary=pd.DataFrame({"Missing Count": missing_count,"Missing %": missing_percent.round(2)}).sort_values("Missing Count", ascending=False)
missing_summary[missing_summary["Missing Count"] > 0]

                Missing Count  Missing %
occupation               1843       5.66
workclass                1836       5.64
native.country            583       1.79

## Task 3

In [11]:
df["workclass"] = df["workclass"].fillna("Unknown")
df["occupation"] = df["occupation"].fillna("Unknown")
df["native.country"] = df["native.country"].fillna("Unknown")
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

## Task 4

In [12]:
print("Exact duplicate rows:", df.duplicated().sum())

Exact duplicate rows: 24

In [13]:
cols_no_target = df.columns.drop("income")
print("Duplicates ignoring income:", df.duplicated(subset=cols_no_target).sum())

Duplicates ignoring income: 25

## Task 5

In [14]:
for col in ["education", "marital.status", "native.country"]:
    print(col, "->", df[col].unique())

education -> ['HS-grad' 'Some-college' '7th-8th' '10th' 'Doctorate' 'Prof-school'
 'Bachelors' 'Masters' '11th' 'Assoc-acdm' 'Assoc-voc' '1st-4th' '5th-6th'
 '12th' '9th' 'Preschool']
marital.status -> ['Widowed' 'Divorced' 'Separated' 'Never-married' 'Married-civ-spouse'
 'Married-spouse-absent' 'Married-AF-spouse']
native.country -> ['United-States' 'Unknown' 'Mexico' 'Greece' 'Vietnam' 'China' 'Taiwan'
 'India' 'Philippines' 'Trinadad&Tobago' 'Canada' 'South'
 'Holand-Netherlands' 'Puerto-Rico' 'Poland' 'Iran' 'England' 'Germany'
 'Italy' 'Japan' 'Hong' 'Honduras' 'Cuba' 'Ireland' 'Cambodia' 'Peru'
 'Nicaragua' 'Dominican-Republic' 'Haiti' 'El-Salvador' 'Hungary'
 'Columbia' 'Guatemala' 'Jamaica' 'Ecuador' 'France' 'Yugoslavia'
 'Scotland' 'Portugal' 'Laos' 'Thailand' 'Outlying-US(Guam-USVI-etc)']

In [30]:
for col in ["education", "marital.status", "native.country"]:
    df[col] = df[col].str.strip()

## Task 6

In [16]:
df.describe()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [17]:
df.describe(include="object")

,workclass,education,marital.status,occupation,relationship,race,sex,native.country,income
count,32561,32561,32561,32561,32561,32561,32561,32561,32561
unique,9,16,7,15,6,5,2,42,2
top,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,<=50K
freq,22696,10501,14976,4140,13193,27816,21790,29170,24720

In [18]:
print("Mean age:", df["age"].mean(), "| Median age:", df["age"].median())
print("Mean hours/week:", df["hours.per.week"].mean(), "| Median hours/week:", df["hours.per.week"].median())

Mean age: 38.58164675532078 | Median age: 37.0
Mean hours/week: 40.437455852092995 | Median hours/week: 40.0

## Task 7

In [19]:
print(df["occupation"].value_counts().head(1))

occupation
Prof-specialty    4140
Name: count, dtype: int64

In [20]:
print(df["sex"].value_counts(normalize=True) * 100)

sex
Male      66.920549
Female    33.079451
Name: proportion, dtype: float64

In [21]:
print(df["income"].value_counts(normalize=True) * 100)

income
<=50K    75.919044
>50K     24.080956
Name: proportion, dtype: float64

## Task 8

In [35]:
check=df.groupby("education")["education.num"].unique()
print(check)

education
10th             [6]
11th             [7]
12th             [8]
1st-4th          [2]
5th-6th          [3]
7th-8th          [4]
9th              [5]
Assoc-acdm      [12]
Assoc-voc       [11]
Bachelors       [13]
Doctorate       [16]
HS-grad          [9]
Masters         [14]
Preschool        [1]
Prof-school     [15]
Some-college    [10]
Name: education.num, dtype: object

In [34]:
inconsistent=check[check.apply(len)>1]
print("Inconsistent mappings:")
print(inconsistent)

Inconsistent mappings:
Series([], Name: education.num, dtype: object)

## Task 9

In [33]:
import sqlite3
conn=sqlite3.connect("adult.db")
df.to_sql("adult_income",conn,if_exists="replace",index=False)
query="SELECT * FROM adult_income WHERE age>30"
sql_df=pd.read_sql_query(query,conn)
print("Original CSV shape:",df.shape)
print("SQL query result shape:",sql_df.shape)

Original CSV shape: (32561, 15)
SQL query result shape: (21989, 15)

## Task 10

**Dataset Overview:** The dataset is US census records used to predict whether an individual earns more than 50K or less than 50K annually.

**Data Quality Issues Found:**
- Missing values found as "?" in workclass, occuptation and native.country.
- Some exact duplicate rows found and more duplicates found when ignoring the income column.
- whitespace inconsistencies in education, marital.status and native,country.

**Key Observations:**
- Income classes are imbalanced because majority of people earns more than 50k..
- Most common occupation identified was found prof=speciality.
- Mean and median age/hours-per-week are close that means that data is symmetric.

**Cleaning Decisions Made:**
- Replaced "?" with NaN to identify missing values.
- Inserted missing categorical values with "Unknown" instead of dropping rows in order to preserve sample size.